### ISSUE TITLE
this is working ???

### ISSUE THREAD

**Issue by ghost** [Titaniumtown/pyfetch#2]
[jayjames@GnuChanOS pyfetch]$ sh compile.sh 
compile.sh: line 4: cython3: command not found
cc1: fatal error: pyfetch.c: No such file or directory
compilation terminated.

-------------------------------------------------------------------------------------
[jayjames@GnuChanOS pyfetch]$ python pyfetch.py 
Traceback (most recent call last):
  File "/home/jayjames/tmp/pyfetch/pyfetch.py", line 275, in <module>
    logo_test()
  File "/home/jayjames/tmp/pyfetch/pyfetch.py", line 260, in logo_test
    sys_info = display_array()
  File "/home/jayjames/tmp/pyfetch/pyfetch.py", line 199, in display_array
    pac_msg, full_cpu_info, product_info, pretty_name, shell, resolution, terminal_emu, kernel, uptime, hostname, gpu, memory = non_debug()
  File "/home/jayjames/tmp/pyfetch/pyfetch.py", line 133, in non_debug
    shell, resolution, terminal_emu, kernel, uptime = misc_func()
  File "/home/jayjames/tmp/pyfetch/pyfetch.py", line 47, in misc_func
    shell_ver = environ['BASH_VERSION'].split('(')[0]
  File "/usr/lib/python3.9/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'BASH_VERSION'

**Comment by Titaniumtown** [comment]
You're not using bash, also the compile.sh was a test using cython to compile to a native binary.

feel free and open a PR implementing multi shell support :p
